import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { StoreProvider } from "@/src/redux/StoreProvider";
import { Toaster } from "react-hot-toast";
import { SocketProvider } from "@/src/utils/socket/socket-provider";
import { AuthProvider } from "@/src/utils/context/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Secure Ride Home",
  description: "Generated by create next app",
  icons: {
    icon: '@/src/assets/logo.png'
  }
  
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="vi">
        <body suppressHydrationWarning={true} className={inter.className}>
          <AuthProvider>
              {children}
              <Toaster position="top-right" />
          </AuthProvider>
        </body>
      </html>
    </StoreProvider>
  );
}
